apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: ingress-basic
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt
    kind: Issuer
  commonName: labelgenius.pics
  dnsNames:
    - labelgenius.pics
