version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "./apigateway"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "./projectservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "./userservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "./communicationservice"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "./authentication"
    schedule:
      interval: "weekly"
