apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: projectservice
          image: zstrox/projectservice:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secret/firebase.json
            - name: BlobStorage__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: BlobStorage__ConnectionString
            - name: BlobStorage__AccountName
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: BlobStorage__AccountName
            - name: BlobStorage__AccountKey
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: BlobStorage__AccountKey
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MongoDbSettings__ConnectionString
            - name: MongoDbSettings__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MongoDbSettings__DatabaseName
            - name: EventHubConfig__EventHubConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: EventHubConfig__EventHubConnectionString
            - name: EventHubConfig__EventHubName
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: EventHubConfig__EventHubName
            - name: EventHubConfig__ConsumerGroupProjectEvents
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: EventHubConfig__ConsumerGroupProjectEvents
            - name: EventHubStorage__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: EventHubStorage__ConnectionString
            - name: EventHubStorage__ContainerProjectEvents
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: EventHubStorage__ContainerProjectEvents
            - name: ServiceBus__QueueName
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: ServiceBus__QueueName
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: ServiceBus__ConnectionString
          volumeMounts:
            - name: json-secret-volume
              mountPath: /var/secret
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: json-secret-volume
          secret:
            secretName: firebase.json
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
