version: '3.8'

services:
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - backend

  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=firebase.json
    networks:
      - backend

networks:
  backend: