version: "3.8"

services:
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - backend

  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=firebase.json
    volumes:
      - ./userservice/firebase.json:/app/firebase.json
      - ./userservice/appsettings.json:/app/appsettings.json
    networks:
      - backend

  projectservice:
    build:
      context: ./projectservice
      dockerfile: Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=firebase.json
    volumes:
      - ./projectservice/firebase.json:/app/firebase.json
      - ./projectservice/appsettings.json:/app/appsettings.json
    networks:
      - backend

  communicationservice:
    build:
      context: ./communicationservice
      dockerfile: Dockerfile
    volumes:
      - ./communicationservice/appsettings.json:/app/appsettings.json
    networks:
      - backend

networks:
  backend:
