apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communicationervice
          image: zstrox/communicationservice:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: AzureCommunication__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AzureCommunication__ConnectionString
            - name: ServiceBus__QueueName
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: ServiceBus__QueueName
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: ServiceBus__ConnectionString
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 50m
              memory: 50M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
