kind: Service
apiVersion: v1
metadata:
  name: user-service
  namespace: ingress-basic
spec:
  ports:
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: user-service
  type: ClusterIP
