name: Stage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build API Gateway
        run: |
          cd ./apigateway
          dotnet restore
          dotnet build

      - name: Build UserService
        run: |
          cd ./userservice
          dotnet add package LabelGenius.Authentication --version 0.0.1 
          dotnet restore
          dotnet build

      - name: Build ProjectService
        run: |
          cd ./projectservice
          dotnet add package LabelGenius.Authentication --version 0.0.1 
          dotnet restore
          dotnet build

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Docker Images
        run: |
          cd ./apigateway
          docker build -t $DOCKER_USERNAME/apigateway:latest .
          docker push $DOCKER_USERNAME/apigateway:latest

          cd ../userservice
          docker build -t $DOCKER_USERNAME/userservice:latest --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_TOKEN=$GITHUB_TOKEN .
          docker push $DOCKER_USERNAME/userservice:latest

          cd ../projectservice
          docker build -t $DOCKER_USERNAME/projectservice:latest --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_TOKEN=$GITHUB_TOKEN .
          docker push $DOCKER_USERNAME/projectservice:latest
