name: Stage

on:
  push:
    branches:
      - main

env:
  GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-deploy:
    strategy:
      matrix:
        service: ["userservice", "projectservice"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Has Changed Path
        id: check_files
        uses: MarceloPrado/has-changed-path@v1.0.1
        with:
          paths: ${{ matrix.service }}/**

      - name: Set up .NET SDK
        if: steps.check_files.outputs.changed == 'true'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Service
        if: steps.check_files.outputs.changed == 'true'
        run: |
          cd ./${{ matrix.service }}
          dotnet add package LabelGenius.Authentication --version 0.0.1 
          dotnet restore
          dotnet build

      - name: Set up Docker Buildx
        if: steps.check_files.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: steps.check_files.outputs.changed == 'true'
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Docker Images
        if: steps.check_files.outputs.changed == 'true'
        run: |
          cd ./${{ matrix.service }}
          docker build -t $DOCKER_USERNAME/${{ matrix.service }}:latest --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_TOKEN=$GITHUB_TOKEN .
          docker push $DOCKER_USERNAME/${{ matrix.service }}:latest
